name: Dart

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Cache Flutter SDK
        uses: actions/cache@v4
        id: flutter-cache
        with:
          path: /opt/hostedtoolcache/flutter
          key: flutter-${{ runner.os }}-${{ hashFiles('fe/**/pubspec.yaml') }}
          restore-keys: |
            flutter-${{ runner.os }}-

      - name: Set up Flutter
        if: steps.flutter-cache.outputs.cache-hit != 'true'
        uses: subosito/flutter-action@v2
        with:
          channel: stable

      - name: Cache pub dependencies
        uses: actions/cache@v4
        with:
          path: ~/.pub-cache
          key: pub-cache-${{ runner.os }}-${{ hashFiles('fe/**/pubspec.yaml') }}
          restore-keys: |
            pub-cache-${{ runner.os }}-

      - name: Set up Java environment
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '11'

      - name: Install dependencies
        run: |
          cd fe
          flutter pub get

      - name: Run build_runner
        run: |
          cd fe
          flutter pub run build_runner build --delete-conflicting-outputs

      - name: Run dart format
        run: |
          cd fe
          dart format --set-exit-if-changed .

      - name: Run flutter analyze
        run: |
          cd fe
          flutter analyze

      - name: Run flutter test
        run: |
          cd fe
          flutter test --no-pub --coverage

      - name: Build APK
        run: |
          cd fe
          flutter build apk --release

      - name: Upload APK
        uses: actions/upload-artifact@v3
        with:
          name: release-apk
          path: fe/build/app/outputs/flutter-apk/app-release.apk
